### ISSUE TITLE
Decentralizing the NIPs registry

### ISSUE THREAD

**Issue by fiatjaf** [nostr-protocol/nips#162]
Would be great if people could agree on NIPs and publish them on Nostr itself, without having to request permission from a cabal of maintainers of a specific GitHub repository.

Then people could see NIP proposals and say they endorse them or not, or point to implemented NIPs by their ids from client and relay implementations.

This could be chaotic at the beginning but I think it would be healthier to the protocol. It would also be nice to not lend all the NIPs an equal status of "officialness" just by them being in this repository.

The sad thing would be that we would lose the cool-sounding NIP numbers.

**Comment by fiatjaf** [comment]
To be honest there are some NIP proposals that I don't like at all and don't want to merge, and while I try to say to myself that I should merge them if there are some people wanting them and they're not completely absurd, I feel like when merging I immediately award them with a special status when they shouldn't have that -- no NIPs should.

**Comment by tmathews** [comment]
I agree, developers should feel free  to experiment and try things. They can release their own NIP for what they have created and if it catches on great. The repo/pr/issue process is acting as a gateway rather than a documentation.

**Comment by andrerfneves** [comment]
Yes to this. Make NIPs great again

**Comment by mikedilger** [comment]
I'm worried.

I get the argument @fiatjaf  that you don't want to be gatekeeper and don't want to be seen as blessing these NIPs. But I think if we don't have some kind of partial consensus or partial centralization, interoperablity will be at risk.

So long as whatever replaces this serves the purpose of extending nostr and also allows us to continue to be interoperable, then my concerns are addressed.

**Comment by 1440000bytes** [comment]
Concept ACK

Bitcoin developers tried doing it but failed<sup>1<sup> although some proposals for Bitcoin exist outside https://github.com/bitcoin/bips repository and implemented in different projects.

Would be a great if nostr protocol has no official registry for NIPs however proposals still get discussed. Instead of NIP numbers, developers can use present year and a unique name for it. Example: `NIP 2023-Ostrich`

<sup>1<sup>Related emails: 

https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-April/018859.html

https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-April/018868.html

https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-April/018869.html

https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-April/018871.html

**Comment by eskema** [comment]
> developers can use present year and a unique name for it

we'll need a decentralized name registry first then.. because who decides what unique name is the right one? maybe a note id would make it unique, and we can petname it?

**Comment by fiatjaf** [comment]
Yes, I agree, an event id is probably better.

I was thinking that just having a "long form editable text" kind would be enough, then we can use that to write NIPs.

**Comment by Cameri** [comment]
Could we use parametrized replaceable events? We just need a client that supports editing and then the conversation can happen on Nostr.

**Comment by fiatjaf** [comment]
I was thinking of doing editable texts using parameterized replaceable events, like this:

```
kind 10 -> article title
kind 11 with `d` tag pointing to article title -> article body that can change
```

**Comment by Cameri** [comment]
> I was thinking of doing editable texts using parameterized replaceable events, like this:
> 
> 
> 
> ```
> 
> kind 10 -> article title
> 
> kind 11 with `d` tag pointing to article title -> article body that can change
> 
> ```
> 
> 
> 
> The problem is that this will not allow anyone to refer to an old version of a NIP.

I was thinking along the same lines.

Not sure if we need kind 10, could just be a kind 1?.
The article body kind should be in the 30k to 40k range and the d tag could be the event ID of the kind 1 post like how the channel metadata event works.

People could comment on the article and suggest improvements w/ patches as git diffs?

**Comment by fiatjaf** [comment]
Right, yes, sorry, I didn't read the NIP before commenting.

I don't think it should be a kind 1 as that will cause these things to show up in social clients feeds and make not very much sense. I think they require special clients (or special support in normal clients), therefore a new kind is better.

But I am thinking this new kind could be used for all sorts of "articles" and to make kind of a medium.com alternative on Nostr, and maybe a Wikipedia alternative on Nostr, not only NIPs, NIPs would be just one immediate use case.

I do however feel sad for not having the ability to reference old versions. If I say I implement and like one specific NIP and then the author changes that completely, where do I stand?

**Comment by jacany** [comment]
We could always store the old content inside of a `h` tag organized by timestamp

Either that or there could be a new kind of replaceable events that has a history feature.
Relays serve the newest one by the tag but if a client want the older ones it has to ask for it

**Comment by Cameri** [comment]
> I don't think it should be a kind 1 as that will cause these things to show up in social clients feeds and make not very much sense. I think they require special clients (or special support in normal clients), therefore a new kind is better.

Yup. Makes sense.

> I do however feel sad for not having the ability to reference old versions. If I say I implement and like one specific NIP and then the author changes that completely, where do I stand?

You are right, replaceable events are not good for this, the history (commits) is important.

I think `kind 10` is fine for starting a new article, and the event ID is the foundational event for anything that follows.
I still think we would need a `kind 11` to change the metadata on `kind 10`. So far metadata can be: title, state (draft, final, etc), authors/editors, publishers (who can publish revisions).

We could have forks so perhaps `kind 10` can reference a previous `kind 10` event.

It almost feels like we'd be recreating `git` IMO with the only difference that you'd be using your Nostr key instead of GPG for signing.

**Comment by fiatjaf** [comment]
But for these other use cases no one cares about the versioning, so it would be unnecessary bloat and make queries huge for basically no reason.

**Comment by fiatjaf** [comment]
The best solution I can think of now is for somewhere a client or a relay specialized in storage to keep track of the specific versions someone ask them to keep, so they can be referenced or restored/forked if overwritten.

**Comment by gkbrk** [comment]
>> kind 11 with `d` tag pointing to article title -> article body that can change
>
> The problem is that this will not allow anyone to refer to an old version of a NIP.

People can still refer to the older versions by the event ID. Replaceable events don't invalidate existing events, just replaces them for a pubkey-kind-tag.

**Comment by melvincarvalho** [comment]
So I think at this early stage there's a need to prevent collisions:

I very quickly made this:

- [json for kinds](https://github.com/nostrdata/kinds/blob/gh-pages/kinds.json) 
- [Live JSON](https://nostrdata.github.io/kinds/kinds.json)

Completely unofficial, of course.  I have no idea if it will be useful or get upstream, but I'll try and keep the list up to date if people add kind numbers.  

Or just take it and put it somewhere in nostr-protocol if desired.

**Comment by mikedilger** [comment]
@melvincarvalho I recently dug through all the PRs to extract all the kinds that might be in use and came up with this list, above and beyond what has been merged it:

  6 - repost (? closed)
  8 - bookmarks (NIP-29)
  8 - poll & vote (NIP-41)
  8 - badges (NIP-58)
  9 - resource  (NIP-30)
  12 - decoy key proof (NIP-24)
  17 - git updates and discovery (NIP-17)
  30 - chess game event
  32 - reputation (NIP-32)
  104 - encrypted group chat (NIP-38)
  140 - encrypted group chat (NIP-38)
  141 - encrypted group chat (NIP-38)
  142 - encrypted group chat (NIP-38)
  143-149 - encrypted group chat (NIP-38)
  4326 - geospatial note (NIP-44)
  9374 - lightning zap request (NIP-57)
  9375 - lightning zap invoice receipts (NIP-57)
  9400 - web-of-trust reputation (PR #203)
  10000 - nostr dns
  10001 - (NIP-23 closed)
  24133 - nostr connect
  30000-30002 lists (NIP-51)
  30008 - badges (NIP-58)
  30023 - long form content
  30303 - relay status (NIP-59)

**Comment by melvincarvalho** [comment]
Work in progress, a little html page that will display NIP numbers from JSON

https://nostrdata.github.io/kinds/

**Comment by melvincarvalho** [comment]
Two very good resources here:

- https://nips.be/search
- https://nips.be/nips-info.json

**Comment by p2w34** [comment]
I understand the idea behind NIP-01 was to constitute the complete basis of the whole protocol. One easy-to-grasp document to demonstrate the thing is straightforward. The cons are that a few things got mixed, limiting its potential.

One could consider splitting NIP-01 into smaller parts without sacrificing backward compatibility, at the same time gaining more flexibility:
1. NIP-00: Decentralized registry (https://github.com/nostr-protocol/nips/issues/162 although more discussions needed)
2. NIP-1a: Base event format with well described types of fields.
a) Only value `1: text_note` as the default one introduced here for `kind`—the rest of the values presented in other NIPs.
b) `algo` field added, with 'secp256k1' being the default. Signing is challenging, as done preferably by hardware wallets, hence more methods should be supported (future NIPs). The verification part is easy (no penalty for screwing it up), and done with any software.
c) The way `id` and `sig` fields are computed should be changed. Instead of saying what fields should be included, one could specify which should not. This way the description stays precise even when new fields are added in future NIPs.
3. NIP-1b: Application protocol (filters/subscriptions). It should be presented in a way that is separated from the communication protocol. The websockets would stay as the default choice, but this would allow the introduction of other forms of communication protocol. I could easily imagine a future NIP with plain HTTP being an alternative - this way I could... store all my posts on any HTTP server.
4. NIP-1c: Event types (`0`: `metadata`, `2`:`recommend_server`).


For me NIP-00 (well, depends on the implementation), NIP-1a and NIP-1b should form the solid basis for the protocol.

**Comment by earonesty** [comment]
I like the idea that people can vote for nips just by clicking the like button!

**Comment by marcusmmmz** [comment]
How would event kinds be assigned? Ideally that would be with a uuid/event id, since then anyone could create their own NIP + the needed event kinds and there would be no collisions (and kind collisions are a bigger problem than NIP collisions). Would that even be possible, considering that kinds are currently represented by numbers?

Having a mostly "blessed" source of -IPs is not a problem generally, Bitcoin for example does just fine having BIPs this way, But Nostr is different because Nostr clients and relays always have the option to not implement a NIP (so it's not like Bitcoin, in which global consensus is needed for a change).

I think the workflow for Nostr should happen in a manner in which it's possible for clients to start innovating alone, NIPs and event kinds being created by them, and later if that functionality is seen to be done in a good way it could be "blessed" just at it is today, and by being blessed i mean recommending that this NIP be used instead of creating a new one. This way there would be a balance between innovation and interoperability.

Either way, what is the expected workflow nowadays? How would I go about choosing an event kind for a new functionality that no other client currently has? Am I expected to actually wait for an event kind to be assigned by the Nostr team before I can start using it?

**Comment by Giszmo** [comment]
I wrote an article on this topic [here](https://habla.nostr.info/a/naddr1qqdxsmmh23h5xmmwwdhkc6tyv96x2nr0den5vmmjd4zkuq3qgm7tuvr9atc6u7q3gevjfeyfyvmrlul4y67k7u7hcxztz67ceexsxpqqqp65wg2apxr). The key take-aways would be:

* pet names: If Alice calls it nip999, people can reference it as Alice.nip999
* e**n**dorsements: If Bob endorses Alice.nip999, Bob.nip999 is the same nip but Carol can also endorse EventId as nip999. For endorsements I suggest an n-tag.
* we need something beyond nip33 to make sure Alice:KindNip:999 returns just one event but as Carol kept the EventId around, it can also be found with an extra round-trip
* In practice, some relays already keep old versions of nip33 events around but it makes sense to make it explicit for this use.

**Comment by Giszmo** [comment]
Proposing #400 to overcome event deletion. Proposed NIP also contains how a nip registry could work.

**Comment by rusteroobs** [comment]
> Decentralizing the NIPs registry 

It would be interesting to write NIPS here: [fostr.dev](https://fostr.dev/)

**Comment by telamon** [comment]
Nice, this is a pretty rad idea.
I did't read all of it. But why not do git push to a relay?
I used a git push helper once to push commits into a hypercore. And SSB I think had something similar. 

You'll need some sort of ux to discover/track the forks, but a "gitstr" would potentially decentralize not only nostr governance but also impact other repos or the way we treat free/open source.

**Comment by melvincarvalho** [comment]
Almost a year on from this we dont have an alternate workflow, let alone a decentralized one.

It might not be the case, but casual observation of the NIPs area is that it's turned into a dictatorship.  Some NIPs if authored by certain people would get prioritized.  Others rejected on principle.

That is maybe as it should be, since open source is always a web of trust.  However it relies on a super human benevolent dictator.  And we certainly dont have that.

Let's propose something better and practical.

Another stream for nips with another workflow.

This NIP repo handles NIPS 1-1000, and they are the core NIPs that are 'official'.

We need an area for 'unoffical' NIPs.  Why dont we allocate numbers 1001-2000 for them, for the time being so that they dont clash.  NIPs rejected from the official NIP repo can be marked experimental and go to the unofficial NIP area.  By going from NIP-XXX -> NIP-2XXX

NIPs that are very good in the unofficial can be taken up as an official 2xxx NIP.  And so on.

Developers get to choose their NIP area and workflow.  Something like that ... thoughts?

**Comment by Giszmo** [comment]
I think we shouldn't take this repo too serious. If your idea has merit, write a nostr long form post about it and implement it in your client. Screw our dictator (fiatjaf we love you ;) ) If the idea is good and others want to interoperate, they will implement it regardless whether a number was assigned. "Melvin's DM scheme" is as good a name as any other. What is it with the drive to have something "official". There is no concept of "official" in a decentralized system.

Also I think it's getting a bit out of hands here anyway. Many nips don't follow the rule that it has to be implemented first by two clients before it gets to be a nip.

**Comment by vitorpamplona** [comment]
I agree with Gizmo. Do you want to describe your NIP somewhere else? Sure! Go for it. 

Anyone can create a NIP repo anywhere. But NIPs are useless by themselves. They are only valuable when they accurately describe an actual implementation that has been shipped AND is doing well. And I think there is no real use (2+clients) of Nostr that have been blocked from publishing their NIPs here. 

There are no official specs. There is only a bunch of devs trying to make their stuff more understandable to others. And for that this repo has been great.

**Comment by AsaiToshiya** [comment]
As #867 informs, kind is more important than NIP to avoid breaking each other.

**Comment by gazhayes** [comment]
We don't need to roll out a complete and final solution all at once, we can take very small steps in a direction that isn't wrong, and see what works and what doesn't. 

Out of principle, I will never submit a NIP to this repository, and the concerns I had a year ago are becoming a reality. I've created a very small PR #867 to test the political will for course correction (before I dedicate time towards solving this problem a different way).

Instead of being a central planning commission that sanctions and gates access to development on nostr on behalf of Jack (go and ask people new to nostr what their impression is), this repo can course correct to become a central planning commission that expresses its educated and well reasoned opinion on NIPs that exist (anywhere) in the wild, making experimentation more palatable.

As soon as a Kind number is actively in use, it can be added to the index in this repo, along with a link to a NIP (on github, as an event, or anywhere else). The bar for this should be VERY low.

The role of the central planning bureau is then to signal their opinion on the current status of the NIP by incrementing its lifecycle status. This converts the honourable members of the politbureau from leaders of the community into advisors to the community.

> I think we shouldn't take this repo too serious. 

We don't control how seriously people take it. To the vast majority, and certainly to anyone new, this repo **is the authority on what is allowed to be done on nostr**. 

This was not the case in the past, but as predicted it's now the situation we are in, and if nothing changes then the ossification will continue, with predictable and counter-revolutionary results.

**Comment by erskingardner** [comment]
I agree with @Giszmo and @vitorpamplona I don't think we need to have a formally defined separate repo. If you want to create something, go for it. That's permissionlessness. I have yet to see any net new NIPs that don't have at least 1 implementation get built, usually there are two, often more than that.

The idea that the NIPs repo is a dictatorship is abdicating the personal responsibility to 

1. clearly describe what your new NIP matters,
2. build consensus/acceptance with peers, and
3. build/beg/borrow/steal to get the new thing implemented in 2 clients. 

The only NIPs PRs that I see wallowing fail at one or more of these and so deserve to wallow until they improve.

Also – @fiatjaf isn't the only person with merge rights, so it's more of a council of priests than a dictatorship. 😂

**Comment by melvincarvalho** [comment]
> isn't the only person with merge rights

But that is not transparent to the public.  It needs to be to attract developers.  It's something that's not obvious to those with merge access, but very obvious to 99% that come to the repo.

Lack of transparency and bike shedding are generally regarded as the biggest 2 killers of open source.

**Comment by melvincarvalho** [comment]
> We don't control how seriously people take it. 

It misses the point.  That the whole this is shrouded in mystery and centralization means that people wont even start or try.  They will go elsewhere.

People do take it seriously because there's no other place to put NIPs, to name NIPs, to get NIPs reviewed, and to coordinate, which is vital in this stage of the project.  

If it's seen as gate kept, and it is seen that way now, development will go elsewhere.  Simple project hygiene that all our competitor do, such as activitypub sees them gain developers who could be building on nostr.  Agree that it doesnt all need be solved in one go.  But the impression is of a dictatorship, and if it isnt, it should be easy to demonstrate.

**Comment by erskingardner** [comment]
> Why not show the world who has commit access? What is there to hide?

Yeah, I agree, the NIPs repo should have a readme or another wiki doc that explains how the NIP repo works, including who has merge rights, and why. Sounds like we have more of a marketing/documentation issue here rather than a procedural issue in how new NIPs are created/merged.

**Comment by melvincarvalho** [comment]
This thread started out as a call to decentralize the the nostr core working process.  Good idea.  

It's now revealed that the current process is a "council of priests" operating in a closed centralized way, that wont even reveal to the public who they are.

No other open project does this.  Why not reveal yourselves on the [github people] page?  It looks dystopian af.  Why is there any resistance at all to being open?

So why not just tell the community who is the council of priests.

**Comment by staab** [comment]
> Why is there any resistance at all to being open?

I don't think there's any resistance, there's just apathy. I personally never use my merge access (hello, you may refer to me as "perfect elu kadosh hodlbod"), and when I do I regret it because I end up being too hasty. Nostr is a high-trust society, no one has abused their merge access (that I've seen). So sure, if it'll make people feel better let's list the maintainers somewhere.

**Comment by AsaiToshiya** [comment]
> It's now revealed that the current process is a "council of priests" operating in a closed centralized way, that wont even reveal to the public who they are.

I don't think so because the acceptance criteria for NIPs are clear. It's just that the interest of the maintainers are a little biased.

**Comment by jb55** [comment]
On Wed, Nov 15, 2023 at 02:31:47PM -0800, Melvin Carvalho wrote:
>This thread started out as a call to decentralize the the nostr core
>working process.  Good idea.
>
>It's now revealed that the current process is a "council of priests"
>operating in a closed centralized way, that wont even reveal to the
>public who they are.

>No other open project does this.  Why not reveal yourselves on the
>[github people] page?  It looks dystopian af.  Why is there any
>resistance at all to being open?

Is there? Who is resisting? If anyone is resisting to this I don't want
to be a part of it.

>So why not just tell the community who is the council of priests.

current list is

@atdixon
@BrightonBC
@Cameri
@eskema
@fiatjaf
@Giszmo
@jb55
@KoalaSat
@mmalmi
@monlovesmango
@ottman

**Comment by staab** [comment]
Hey, what about me

**Comment by jb55** [comment]
I was just listing people from the https://github.com/orgs/nostr-protocol/people page like @melvincarvalho mentioned. maybe you're specifically on the nips repo?

**Comment by staab** [comment]
Yeah, I think most people probably are? @Giszmo is the only one publicly visible on the org

**Comment by Giszmo** [comment]
I would suggest to make it a requirement for members to be public. @jb55 did what I was tempted to do - share the list without asking.

How about removing all members that do not set their membership to "public" by end of next week?

I don't particularly care about being a member as I did not use that privilege in months and removing unused privileges is a good security habit anyway but I do care about members being public.

I know https://github.com/orgs/nostr-protocol/people but I fail to find members of https://github.com/nostr-protocol/nips

**Comment by staab** [comment]
Ok, so I've looked and I don't know how to set my visibility as public.

**Comment by fiatjaf** [comment]
I've just invited everybody who was in the nips repo to the nostr-protocol group.

**Comment by staab** [comment]
Behold, the priests reveal themselves in their shining spotless garments, to bring down the oracles of heaven for the mere mob that waits with bated breath to be told how they might speak with one another. Their fears are quelled, doubts stilled, the earth runneth with fat and honey, mothers give birth without pain, and all is well.

![Screenshot 2023-11-16 at 11 00 35 AM](https://github.com/nostr-protocol/nips/assets/2494842/b1510629-2cce-440c-aefd-7f4f2cba0dc0)

@melvincarvalho, I really don't appreciate how you forced this issue. You could have brought this forward in a cooperative fashion. Instead, you chose to sow doubt among nostr plebs instead.

![Screenshot 2023-11-16 at 11 07 31 AM](https://github.com/nostr-protocol/nips/assets/2494842/d5c8669d-2ec1-447b-9da1-b4315d300ef7)
![Screenshot 2023-11-16 at 11 06 37 AM](https://github.com/nostr-protocol/nips/assets/2494842/03ecf437-ba02-413d-8c77-9086f8f21f4a)
![Screenshot 2023-11-16 at 11 06 06 AM](https://github.com/nostr-protocol/nips/assets/2494842/a1d858db-aca4-492a-b72a-458fc7eca6cc)
![Screenshot 2023-11-16 at 11 04 55 AM](https://github.com/nostr-protocol/nips/assets/2494842/75e17868-f662-4cba-91da-29b7580bf67b)

I hope you see now that you're the only one acting in bad faith here.

**Comment by jb55** [comment]
> Ok, so I've looked and I don't know how to set my visibility as public.

I don't either, I didn't even know it was private

**Comment by pablof7z** [comment]
Yeah, it's very hidden, I also had to look to reveal myself:

https://github.com/orgs/nostr-protocol/people

**Comment by pablof7z** [comment]
current users who still have it as private:

@alexgleason @atdixon @BrightonBTC @Cameri @eskema @jb55 @mmalmi @ottman @Semisol @verbiricha

**Comment by staab** [comment]
Maybe a `CONTRIBUTORS` file would be a better way to do this. https://github.com/nostr-protocol/nips/pull/883#issuecomment-1816737715

**Comment by vitorpamplona** [comment]
Contributors with npubs, not with GitHub users.

**Comment by fiatjaf** [comment]
I think a CONTRIBUTORS file solves nothing, and having merge powers isn't the same thing as "contributing".

**Comment by staab** [comment]
What I meant was to have multiple sections. I.e. "owners" "merge-access" and "contributors". This would certainly get out of date but at least people could send PRs to it if they want their name on something.

**Comment by alexgleason** [comment]
You can get a list of contributors from the repo and display it however you want. Let me show you a thing I created in Next.js. On the Soapbox website, we pull the top contributors from GitLab in the past 30 days, and display the top 4 contributors with their avatars. Then in the background, we display an activity graph of commits over time:

![image](https://github.com/nostr-protocol/nips/assets/3639540/89c4588e-c722-47b3-b171-426aba160e68)

https://soapbox.pub/

This is related to #883. I want people to realize that git already has all that information, information is not lost, and that it's just a matter of displaying it on a webpage if we want to do so. GitHub simply doesn't choose to prominently display it somewhere on GitHub itself, but we can still display it somewhere.

I used the GitLab API for my project, but you could use GitHub API, or even clone the repo locally and use git itself. I use a scheduled CI to rebuild the site every night; point is, it can all be automated.

If we decentralize NIPs, then author information would be available on Nostr itself, and it would be possible to do the exact same thing.

**Comment by staab** [comment]
@alexgleason I told Melvin this and he ignored me. I do think it's a bad idea to couple everything to github though.

**Comment by fiatjaf** [comment]
Honestly this obsession with knowing who has merge access is counterproductive and paranoic. The list has no meaning, it can be changed anytime by me and the repository history can be rewritten.

**Comment by Giszmo** [comment]
The obsession with knowing who has merge access goes to show which importance some attribute to this repository which would be a non-issue if we had a decentralized NIP registry.

Maybe it is paranoic but paranoid people will make noise and paranoid people are certainly over-represented among those worried about censorship and free speech.

The list has meaning to some or we wouldn't be talking about it.

Yes, you can change it as the repo owner. So what?

The history can be rewritten but not without being very much detectable. The repo was cloned to a thousand machines that would all notice the change.

So why not either kick those who don't want to be public or agree on it being totally ok to do what jb55 already did anyway and share the list of all whenever anybody asks for it?

**Comment by fiatjaf** [comment]
I don't disagree with that at all. I'm all for sharing the list, and I had done it multiple times before, including once to Melvin like a month ago when he complained about it on the Telegram group. He remains the only person complaining about this as far as I know.

I agree to kick everybody who don't set themselves to public on the organization.

**Comment by weex** [comment]
Added the PR above because I think there's something nice about the list being explicit and managed via git. If someone wants to join or leave they submit a PR. Not sure this issue is solvable in the classic sense but this can be progress.

**Comment by pablof7z** [comment]
I think having an explicit list of maintainers in a file makes it worse, if anything, I think @vitorpamplona 's autogenerated image is better as it's implied that it's generated from git activity, but an explicit file is weird.

Overall I think this whole thing is a non-problem.

**Comment by weex** [comment]
61 comments over 10 months doesn't seem like a non-problem, but in long meandering issues like this it's easy to oversimplify.

In this issue we have the following problems mentioned:

* the need to request permission from a cabal of maintainers (fiatjaf)
* this repo grants special status to documents which are merged (fiatjaf)
* interoperability could be at risk (mikedilger)
* NIP id uniqueness (eskema)
* ability to refer to old versions of NIPs (fiatjaf)
* NIPs as kind:1 notes would clutter up feeds (fiatjaf)
* kind collisions (melvincarvalho)
* "blessed" IDs are an unnecessary constraint in a system that doesn't require consensus (marcusmmmz)
* the NIPs area has turned into a dictatorship without a super human benevolent dictator (melvincarvalho)
* NIPs don't follow the two implementations rule (giszmo)
* this repo is seen as the authority to newcomers which will lead to ossification (gazhayes)
* merge access isn't transparent which is obvious to new developers (melvincarvalho)
* there is no doc that explains how the NIP repo works, including who has merge rights, and why (erskingardner)
* the interest[s] of the maintainers are a little biased (asaitoshiya)
* github visibility controls are very hidden (pablof7z)
* this obsession with knowing who has merge access is counterproductive and paranoic (fiatjaf)

When I get some time I'll break this out or link in a handful of issues to do with the mechanics of decentralizing the protocol and others to do with managing this github repo. Then it'd probably be a good idea to close this issue. My 2 cents as a pleb.

**Comment by telamon** [comment]
@weex thank you for the summary.
The problem in it's simplicity is that you can't decentralize a git repo using centralized tools.
And some of the tools required to decentralize are currently being designed within this repo.

It's a non-problem that becomes a problem only IF you attempt to solve it - my cent:
Let it go, be kind, have fun. 
:'-)

**Comment by decentropy** [comment]
Re-imagining NIPs is a neat idea... I actually stumbled across this issue, because I think some NIPS are not flushed out (e.g. user statuses) & don't really know where to discuss.

First... I don't think there should be NIP #s. 
I think documentation should be organized by Event Kind #. (Why make people remember two sets of numbers?)

I sometimes use https://nostrapp.link to look up event kind, and see what apps use them.
I think a site like this, that adds discussion and (somehow) allows updateable wiki-like documentation would be great.
The rule of thumb, requiring 2 or more apps before a feature is considered "accepted" seems good... but a place to draft & discuss new feature prototypes & ideas makes sense.

**Comment by marcodpt** [comment]
NIPS must be centralized, but instead of following the opinion of leaders or good ideas from the community, the repository must have the philosophy of documenting market practices.

So the people involved in the repository must be characteristic of researching what relay and app implementations are doing, and only when a practice is very successful or a market standard be documented.

This is exactly how Roman law (the most successful case of private legislation in history) worked.

And this is how the first and only decentralized social network should proceed.

**Comment by fiatjaf** [comment]
That's one of the goals of this repo: to document what is being done.

But also having a discussion with other interested people before you conclude your implementation is also a healthy practice otherwise people will implement the same thing in multiple ways and whoever has the most popular implementation will always win even if their implementation could have been much improved by just talking a little bit with others with open mind and vice-versa. If everybody is happy and have their voice heard and their opinions considered that gives a much stronger basis for a nice interoperable protocol. Providing such a discussion space has been another goal of this repo -- although having the discussion happen somewhere else more nostric would be better, we still don't have that place.

**Comment by marcodpt** [comment]
I read what was written in the repository's objectives, and I almost completely agree.

What I think is that if the proposals were discussed in a draft environment, and implemented by interested relays and customers and only after a certain market success were documented in the NIPs, it would greatly reduce any problems of backward compatibility or depracated NIPs.

But anyway I would like to thank the community for the wonderful work and in my view the protocol is the king and nostr has been the winner since NIP 01

**Comment by marcodpt** [comment]
In my personal opinion, git is better for persisting data like a book or documentation, so nothing beats having this material written and, if necessary, replicated on several git hosts.

But nostr is infinitely better for creating a community, something like a slack based on nostr would be a very good app for discussions, topics and proposals through a community that cannot be destroyed by any imposition.

**Comment by RandyMcMillan** [comment]
👀
